"""add_sessions_messages_workflows

Revision ID: 1735af9e88fb
Revises: d4e574d1b4a2
Create Date: 2026-03-31 17:55:22.436661

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1735af9e88fb"
down_revision: str | None = "d4e574d1b4a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
