"""add_sessions_messages_workflows

Revision ID: 1735af9e88fb
Revises: d4e574d1b4a2
Create Date: 2026-03-31 17:55:22.436661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1735af9e88fb'
down_revision: Union[str, None] = 'd4e574d1b4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
