"""add_sessions_messages_workflows

Revision ID: 6d972f01c643
Revises: b4a2810feed3
Create Date: 2026-03-31 17:47:25.712840

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6d972f01c643"
down_revision: str | None = "b4a2810feed3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
