"""add telemetry columns

Revision ID: a55b3c3e98f0
Revises: 16d981d95c62
Create Date: 2026-04-03 12:12:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a55b3c3e98f0"
down_revision: str | None = "16d981d95c62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by manually writing the migration ###
    op.add_column("messages", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("output_tokens", sa.Integer(), nullable=True))
    op.add_column("messages", sa.Column("cost_usd", sa.Float(), nullable=True))
    op.add_column("messages", sa.Column("model", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by manually writing the migration ###
    op.drop_column("messages", "model")
    op.drop_column("messages", "cost_usd")
    op.drop_column("messages", "output_tokens")
    op.drop_column("messages", "input_tokens")
    # ### end Alembic commands ###
