"""add_sessions_messages_workflows

Revision ID: d4e574d1b4a2
Revises: 6d972f01c643
Create Date: 2026-03-31 17:50:38.261070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4e574d1b4a2'
down_revision: Union[str, None] = '6d972f01c643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
